name: lint-and-test
on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm
      - uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - run: yarn --cwd=functions --frozen-lockfile
      - run: yarn --cwd=functions lint
      - run: yarn --cwd=functions build
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE test;' -uroot -proot
      - run: yarn --cwd=functions migration:ci
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.5.7
        env:
          CC_TEST_REPORTER_ID: 4031df297e7e3baf9f876cda57686d15060de19c611d5b94f76b64e5ae7999fb
        with:
          coverageCommand: yarn --cwd=functions test:ci
          coverageLocations: ${{github.workspace}}/functions/coverage/lcov.info:lcov
          prefix: ${{github.workspace}}/functions
          debug: true
